import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({ baseDirectory: import.meta.dirname })

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'out/**',
      'build/**',
      // Auto-generated by Next.js; must not be hand-edited.
      'next-env.d.ts',
    ],
  },
  {
    // Frontend only ever talks to the backend via fetch to NEXT_PUBLIC_API_URL.
    // Guard against accidentally leaking secrets into the browser bundle.
    // Also: the browser WebSocket layer never uses the page's console for
    // production logging; warn on stray console.* so it stays clean.
    rules: {
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
]

export default config